ALTER TABLE courses DROP COLUMN likeCount;
ALTER TABLE courses DROP COLUMN dislikeCount;
ALTER TABLE courses DROP COLUMN viewCount;
ALTER TABLE courses DROP COLUMN commentCount;

ALTER TABLE courses ADD COLUMN likeCount INTEGER DEFAULT 0;
ALTER TABLE courses ADD COLUMN dislikeCount INTEGER DEFAULT 0;
ALTER TABLE courses ADD COLUMN viewCount INTEGER DEFAULT 0;
ALTER TABLE courses ADD COLUMN commentCount INTEGER DEFAULT 0;